CREATE TABLE pedidos (
    ID_MESA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    FECHA_PEDIDO DATE NOT NULL,
    PRIMARY KEY (ID_MESA, ID_CLIENTE, ID_PRODUCTO, FECHA_PEDIDO)
);
